import type { BookItem } from "./api";

export interface DemoBookItem extends BookItem {
  likes: number;
  reads: number;
  rating: number;
  isPaid: boolean;
  price: number;
  pageCount: number;
  description: string;
}

export const demoBooks: DemoBookItem[] = [
  {
    bookId: "demo-1",
    title: "달빛 요정의 모험",
    coverImageUrl: "https://picsum.photos/seed/fairy1/400/560",
    authorName: "하늘별",
    likes: 342,
    reads: 1580,
    rating: 4.8,
    isPaid: false,
    price: 0,
    pageCount: 12,
    description: "어느 보름달 밤, 작은 요정 루나가 잃어버린 별을 찾아 떠나는 모험 이야기.",
  },
  {
    bookId: "demo-2",
    title: "숲속 친구들의 비밀",
    coverImageUrl: "https://picsum.photos/seed/forest2/400/560",
    authorName: "초록나무",
    likes: 289,
    reads: 1230,
    rating: 4.7,
    isPaid: true,
    price: 3000,
    pageCount: 16,
    description: "깊은 숲속에서 동물 친구들이 발견한 신비로운 보물 상자의 비밀.",
  },
  {
    bookId: "demo-3",
    title: "바다 위의 별",
    coverImageUrl: "https://picsum.photos/seed/ocean3/400/560",
    authorName: "파도소리",
    likes: 256,
    reads: 980,
    rating: 4.9,
    isPaid: true,
    price: 2500,
    pageCount: 10,
    description: "바다 위에 떠 있는 별을 잡으러 떠나는 작은 물고기의 이야기.",
  },
  {
    bookId: "demo-4",
    title: "구름 위의 성",
    coverImageUrl: "https://picsum.photos/seed/cloud4/400/560",
    authorName: "하늘별",
    likes: 198,
    reads: 870,
    rating: 4.5,
    isPaid: false,
    price: 0,
    pageCount: 14,
    description: "구름 위에 숨겨진 성에 사는 거인과 친구가 되는 소녀의 이야기.",
  },
  {
    bookId: "demo-5",
    title: "마법의 정원",
    coverImageUrl: "https://picsum.photos/seed/garden5/400/560",
    authorName: "꽃잎",
    likes: 175,
    reads: 760,
    rating: 4.6,
    isPaid: true,
    price: 3500,
    pageCount: 18,
    description: "말하는 꽃들이 가득한 마법 정원에서 벌어지는 신기한 하루.",
  },
  {
    bookId: "demo-6",
    title: "무지개 다리",
    coverImageUrl: "https://picsum.photos/seed/rainbow6/400/560",
    authorName: "색동이",
    likes: 163,
    reads: 650,
    rating: 4.4,
    isPaid: false,
    price: 0,
    pageCount: 8,
    description: "비 온 뒤 나타나는 무지개 다리를 건너면 어디로 갈 수 있을까?",
  },
  {
    bookId: "demo-7",
    title: "별빛 기차",
    coverImageUrl: "https://picsum.photos/seed/train7/400/560",
    authorName: "달빛",
    likes: 145,
    reads: 590,
    rating: 4.7,
    isPaid: true,
    price: 2000,
    pageCount: 12,
    description: "밤하늘을 달리는 별빛 기차를 타고 은하수 여행을 떠나는 이야기.",
  },
  {
    bookId: "demo-8",
    title: "용감한 작은 곰",
    coverImageUrl: "https://picsum.photos/seed/bear8/400/560",
    authorName: "산들바람",
    likes: 132,
    reads: 540,
    rating: 4.3,
    isPaid: false,
    price: 0,
    pageCount: 10,
    description: "겁이 많던 작은 곰이 친구를 구하기 위해 용기를 내는 이야기.",
  },
  {
    bookId: "demo-9",
    title: "시간의 모래시계",
    coverImageUrl: "https://picsum.photos/seed/time9/400/560",
    authorName: "시계탑",
    likes: 210,
    reads: 920,
    rating: 4.8,
    isPaid: true,
    price: 4000,
    pageCount: 20,
    description: "할아버지의 다락방에서 발견한 모래시계가 시간을 되돌려준다면?",
  },
  {
    bookId: "demo-10",
    title: "꿈꾸는 인형",
    coverImageUrl: "https://picsum.photos/seed/doll10/400/560",
    authorName: "솜사탕",
    likes: 188,
    reads: 810,
    rating: 4.5,
    isPaid: true,
    price: 2500,
    pageCount: 14,
    description: "밤마다 움직이는 인형이 주인을 위해 준비하는 깜짝 선물.",
  },
  {
    bookId: "demo-11",
    title: "하늘을 나는 고래",
    coverImageUrl: "https://picsum.photos/seed/whale11/400/560",
    authorName: "바다솔",
    likes: 156,
    reads: 680,
    rating: 4.6,
    isPaid: false,
    price: 0,
    pageCount: 12,
    description: "바다가 아닌 하늘을 헤엄치고 싶은 아기 고래의 꿈.",
  },
  {
    bookId: "demo-12",
    title: "마지막 눈사람",
    coverImageUrl: "https://picsum.photos/seed/snow12/400/560",
    authorName: "겨울별",
    likes: 201,
    reads: 890,
    rating: 4.9,
    isPaid: true,
    price: 3000,
    pageCount: 16,
    description: "봄이 와도 녹지 않는 특별한 눈사람과 소녀의 우정 이야기.",
  },
];

export const demoPaidBooks: DemoBookItem[] = demoBooks.filter((b) => b.isPaid);
export const demoFreeBooks: DemoBookItem[] = demoBooks.filter((b) => !b.isPaid);

// 인기순 정렬
export const demoPopularBooks = [...demoBooks].sort((a, b) => b.reads - a.reads);
export const demoPaidPopularBooks = [...demoPaidBooks].sort((a, b) => b.reads - a.reads);
